### ISSUE TITLE
Bands become more and more delayed with time by themselves

### ISSUE THREAD

**Issue by VincyZed** [igorski/delirion#1]
Hi there,

I just tried Delirion for the first time in FL Studio. Sounds like a lot of fun!

However I noticed an odd behavior which I'm not sure is intended: After loading and increasing the Odd and Even parameters for the Mid band for instance, I noticed that there was a delay that was increasingly long for all three bands (but more so if the Odd and Even parameter are turned up for a band) with time,

- This delay resets if I bypass the plugin and turn it back on.
- Turning on Use Fixed Buffer Size does the same thing as bypassing and un-bypassing, that is only fixing the issue temporarily.
- Changing my audio's interface buffer size did not make any difference.
- I haven't tried changing the sample rate, but I'm using 44.1 Khz.
- I'm running the latest version of FL Studio.

Just wanted to report this to make sure this wasn't intended behavior. Sounds cool as a multiband delay too for that matter (lol), but very unpredictable.

I've included an audio example of me playing a saw wave to illustrate the issue.
You'll notice that I have the mix set to below half-way. I also want to mention that this delay does not affect the dry signal.

[Delerion_latency.zip](https://github.com/user-attachments/files/16818725/Delerion_latency.zip)

**Comment by igorski** [comment]
Hi @VincyZed ,

Thanks for your report. 

The behaviour you specify is actually inherent to the Doppler effect, as it is modulated continuously through an LFO. As such, this introduces a small but cumulative drift causing the processed signal to gradually fall out of sync with the original.

However, to function more like a traditional chorus we could consider introducing a beat sync that snaps the oscillators back making the playback of the effected signal align more with the input.

**Comment by igorski** [comment]
This has been resolved in Delirion version 1.1.0, available both in the master branch and as download on the website.
